# Generated by Django 4.0.3 on 2022-03-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='is_archived',
        ),
    ]
